-- Добавляем новые поля для детального описания работ
ALTER TABLE works ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE works ADD COLUMN IF NOT EXISTS download_url TEXT;
ALTER TABLE works ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE works ADD COLUMN IF NOT EXISTS pages INTEGER;
ALTER TABLE works ADD COLUMN IF NOT EXISTS price INTEGER;
ALTER TABLE works ADD COLUMN IF NOT EXISTS specializations TEXT;
ALTER TABLE works ADD COLUMN IF NOT EXISTS keywords TEXT;